# Generated by Django 5.2.4 on 2025-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
