# Generated by Django 5.2.4 on 2025-07-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quizdata1_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentScore', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
