# Generated by Django 5.2.4 on 2025-07-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roomparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(unique=True)),
                ('quizId', models.IntegerField()),
                ('question', models.TextField(max_length=255)),
                ('answer_letters', models.JSONField(blank=True, null=True)),
                ('answer_full', models.TextField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(unique=True)),
                ('quizId', models.IntegerField()),
                ('question', models.TextField(max_length=255)),
                ('answer_letters', models.JSONField(blank=True, null=True)),
                ('answer_full', models.TextField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('finalScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentSeq', models.IntegerField(default=0)),
                ('answerTime', models.BooleanField(default=False)),
                ('quizId', models.IntegerField()),
                ('questionId', models.IntegerField()),
                ('isCorrect', models.BooleanField(default=False)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_room_id', to='main.room')),
                ('roomPK_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_room_pk', to='main.room')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalQuestions', models.IntegerField(default=0)),
                ('correctAnswers', models.IntegerField(default=0)),
                ('finalScore', models.IntegerField(default=0)),
                ('finalRank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
