# Generated by Django 5.2.4 on 2025-07-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_item'),
        ('main', '0003_alter_room_id'),
    ]

    operations = [
    ]
