# Generated by Django 5.2.4 on 2025-07-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quizdata2_quizdata3_ranking_answer_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_answers', to='main.room'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='roomPK_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomPK_answers', to='main.room'),
        ),
        migrations.CreateModel(
            name='Participantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
