# Generated by Django 5.2.4 on 2025-07-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quizdata2_quizdata3_ranking_answer_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_answers', to='main.room'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='roomPK_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomPK_answers', to='main.room'),
        ),
        migrations.AlterField(
            model_name='roomparticipants',
            name='roomId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomparticipants',
            name='uuid',
            field=models.IntegerField(unique=True),
        ),
    ]
