# Generated by Django 5.2.4 on 2025-07-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_0002_user_delete_item_0003_alter_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizData1',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('quizId', models.IntegerField()),
                ('question', models.TextField(max_length=255)),
                ('answer_letters', models.CharField(max_length=255)),
                ('answer_full', models.TextField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
