# Generated by Django 5.2.4 on 2025-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answer_roomid_alter_answer_roompk_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipants',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
