# Generated by Django 5.2.4 on 2025-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_roomparticipants_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipants',
            name='uuid',
            field=models.TextField(unique=True),
        ),
    ]
