# Generated by Django 5.2.4 on 2025-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_roomparticipants_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='roomId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='roomPK_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='quizdata1',
            name='answer_letters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata2',
            name='answer_letters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata3',
            name='answer_letters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='uuid',
            field=models.TextField(unique=True),
        ),
    ]
