# Generated by Django 5.2.4 on 2025-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_answer_roomid_alter_answer_roompk_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
