# Generated by Django 5.2.4 on 2025-07-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roomparticipants',
            name='uuid',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipants',
            unique_together={('roomId', 'uuid')},
        ),
    ]
