# Generated by Django 5.2.4 on 2025-07-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_answer_uuid'),
        ('main', '0011_alter_answer_uuid_alter_roomparticipants_uuid_and_more'),
    ]

    operations = [
    ]
